robot_3:
  controller_manager:
    ros__parameters:
      update_rate: 100  # Hz

      forward_velocity_controller:
        type: forward_command_controller/ForwardCommandController

      forward_position_controller:
        type: forward_command_controller/ForwardCommandController

      joint_state_broadcaster:
        type: joint_state_broadcaster/JointStateBroadcaster

  forward_velocity_controller:
    ros__parameters:
      joints:
        - robot_3_rl_wheel_joint
        - robot_3_rr_wheel_joint      
      interface_name: velocity
      command_interfaces:
        - velocity
      state_interfaces:
        - velocity

  forward_position_controller:
    ros__parameters:
      joints:
        - robot_3_front_left_knuckle_joint
        - robot_3_front_right_knuckle_joint
      interface_name: position
      command_interfaces:
        - position
      state_interfaces:
        - position
